// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sui/rpc/v2beta/epoch.proto

package v2beta

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Epoch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Epoch *uint64                `protobuf:"varint,1,opt,name=epoch,proto3,oneof" json:"epoch,omitempty"`
	// The committee governing this epoch.
	Committee       *ValidatorCommittee  `protobuf:"bytes,2,opt,name=committee,proto3,oneof" json:"committee,omitempty"`
	FirstCheckpoint *uint64              `protobuf:"varint,4,opt,name=first_checkpoint,json=firstCheckpoint,proto3,oneof" json:"first_checkpoint,omitempty"`
	LastCheckpoint  *uint64              `protobuf:"varint,5,opt,name=last_checkpoint,json=lastCheckpoint,proto3,oneof" json:"last_checkpoint,omitempty"`
	Start           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=start,proto3,oneof" json:"start,omitempty"`
	End             *timestamp.Timestamp `protobuf:"bytes,7,opt,name=end,proto3,oneof" json:"end,omitempty"`
	// Reference gas price denominated in MIST
	ReferenceGasPrice *uint64         `protobuf:"varint,8,opt,name=reference_gas_price,json=referenceGasPrice,proto3,oneof" json:"reference_gas_price,omitempty"`
	ProtocolConfig    *ProtocolConfig `protobuf:"bytes,9,opt,name=protocol_config,json=protocolConfig,proto3,oneof" json:"protocol_config,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Epoch) Reset() {
	*x = Epoch{}
	mi := &file_sui_rpc_v2beta_epoch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Epoch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Epoch) ProtoMessage() {}

func (x *Epoch) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta_epoch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Epoch.ProtoReflect.Descriptor instead.
func (*Epoch) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta_epoch_proto_rawDescGZIP(), []int{0}
}

func (x *Epoch) GetEpoch() uint64 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

func (x *Epoch) GetCommittee() *ValidatorCommittee {
	if x != nil {
		return x.Committee
	}
	return nil
}

func (x *Epoch) GetFirstCheckpoint() uint64 {
	if x != nil && x.FirstCheckpoint != nil {
		return *x.FirstCheckpoint
	}
	return 0
}

func (x *Epoch) GetLastCheckpoint() uint64 {
	if x != nil && x.LastCheckpoint != nil {
		return *x.LastCheckpoint
	}
	return 0
}

func (x *Epoch) GetStart() *timestamp.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Epoch) GetEnd() *timestamp.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *Epoch) GetReferenceGasPrice() uint64 {
	if x != nil && x.ReferenceGasPrice != nil {
		return *x.ReferenceGasPrice
	}
	return 0
}

func (x *Epoch) GetProtocolConfig() *ProtocolConfig {
	if x != nil {
		return x.ProtocolConfig
	}
	return nil
}

var File_sui_rpc_v2beta_epoch_proto protoreflect.FileDescriptor

const file_sui_rpc_v2beta_epoch_proto_rawDesc = "" +
	"\n" +
	"\x1asui/rpc/v2beta/epoch.proto\x12\x0esui.rpc.v2beta\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$sui/rpc/v2beta/protocol_config.proto\x1a\x1esui/rpc/v2beta/signature.proto\"\xb3\x04\n" +
	"\x05Epoch\x12\x19\n" +
	"\x05epoch\x18\x01 \x01(\x04H\x00R\x05epoch\x88\x01\x01\x12E\n" +
	"\tcommittee\x18\x02 \x01(\v2\".sui.rpc.v2beta.ValidatorCommitteeH\x01R\tcommittee\x88\x01\x01\x12.\n" +
	"\x10first_checkpoint\x18\x04 \x01(\x04H\x02R\x0ffirstCheckpoint\x88\x01\x01\x12,\n" +
	"\x0flast_checkpoint\x18\x05 \x01(\x04H\x03R\x0elastCheckpoint\x88\x01\x01\x125\n" +
	"\x05start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x05start\x88\x01\x01\x121\n" +
	"\x03end\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x05R\x03end\x88\x01\x01\x123\n" +
	"\x13reference_gas_price\x18\b \x01(\x04H\x06R\x11referenceGasPrice\x88\x01\x01\x12L\n" +
	"\x0fprotocol_config\x18\t \x01(\v2\x1e.sui.rpc.v2beta.ProtocolConfigH\aR\x0eprotocolConfig\x88\x01\x01B\b\n" +
	"\x06_epochB\f\n" +
	"\n" +
	"_committeeB\x13\n" +
	"\x11_first_checkpointB\x12\n" +
	"\x10_last_checkpointB\b\n" +
	"\x06_startB\x06\n" +
	"\x04_endB\x16\n" +
	"\x14_reference_gas_priceB\x12\n" +
	"\x10_protocol_configB\x10Z\x0esui/rpc/v2betab\x06proto3"

var (
	file_sui_rpc_v2beta_epoch_proto_rawDescOnce sync.Once
	file_sui_rpc_v2beta_epoch_proto_rawDescData []byte
)

func file_sui_rpc_v2beta_epoch_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2beta_epoch_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2beta_epoch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2beta_epoch_proto_rawDesc), len(file_sui_rpc_v2beta_epoch_proto_rawDesc)))
	})
	return file_sui_rpc_v2beta_epoch_proto_rawDescData
}

var file_sui_rpc_v2beta_epoch_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sui_rpc_v2beta_epoch_proto_goTypes = []any{
	(*Epoch)(nil),               // 0: sui.rpc.v2beta.Epoch
	(*ValidatorCommittee)(nil),  // 1: sui.rpc.v2beta.ValidatorCommittee
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*ProtocolConfig)(nil),      // 3: sui.rpc.v2beta.ProtocolConfig
}
var file_sui_rpc_v2beta_epoch_proto_depIdxs = []int32{
	1, // 0: sui.rpc.v2beta.Epoch.committee:type_name -> sui.rpc.v2beta.ValidatorCommittee
	2, // 1: sui.rpc.v2beta.Epoch.start:type_name -> google.protobuf.Timestamp
	2, // 2: sui.rpc.v2beta.Epoch.end:type_name -> google.protobuf.Timestamp
	3, // 3: sui.rpc.v2beta.Epoch.protocol_config:type_name -> sui.rpc.v2beta.ProtocolConfig
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2beta_epoch_proto_init() }
func file_sui_rpc_v2beta_epoch_proto_init() {
	if File_sui_rpc_v2beta_epoch_proto != nil {
		return
	}
	file_sui_rpc_v2beta_protocol_config_proto_init()
	file_sui_rpc_v2beta_signature_proto_init()
	file_sui_rpc_v2beta_epoch_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2beta_epoch_proto_rawDesc), len(file_sui_rpc_v2beta_epoch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sui_rpc_v2beta_epoch_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2beta_epoch_proto_depIdxs,
		MessageInfos:      file_sui_rpc_v2beta_epoch_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2beta_epoch_proto = out.File
	file_sui_rpc_v2beta_epoch_proto_goTypes = nil
	file_sui_rpc_v2beta_epoch_proto_depIdxs = nil
}
