// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sui/rpc/v2beta/ledger_service.proto

package v2beta

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServiceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceInfoRequest) Reset() {
	*x = GetServiceInfoRequest{}
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceInfoRequest) ProtoMessage() {}

func (x *GetServiceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServiceInfoRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta_ledger_service_proto_rawDescGZIP(), []int{0}
}

type GetServiceInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The chain identifier of the chain that this node is on.
	//
	// The chain identifier is the digest of the genesis checkpoint, the
	// checkpoint with sequence number 0.
	ChainId *string `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3,oneof" json:"chain_id,omitempty"`
	// Human-readable name of the chain that this node is on.
	//
	// This is intended to be a human-readable name like `mainnet`, `testnet`, and so on.
	Chain *string `protobuf:"bytes,2,opt,name=chain,proto3,oneof" json:"chain,omitempty"`
	// Current epoch of the node based on its highest executed checkpoint.
	Epoch *uint64 `protobuf:"varint,3,opt,name=epoch,proto3,oneof" json:"epoch,omitempty"`
	// Checkpoint height of the most recently executed checkpoint.
	CheckpointHeight *uint64 `protobuf:"varint,4,opt,name=checkpoint_height,json=checkpointHeight,proto3,oneof" json:"checkpoint_height,omitempty"`
	// Unix timestamp of the most recently executed checkpoint.
	Timestamp *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	// The lowest checkpoint for which checkpoints and transaction data are available.
	LowestAvailableCheckpoint *uint64 `protobuf:"varint,6,opt,name=lowest_available_checkpoint,json=lowestAvailableCheckpoint,proto3,oneof" json:"lowest_available_checkpoint,omitempty"`
	// The lowest checkpoint for which object data is available.
	LowestAvailableCheckpointObjects *uint64 `protobuf:"varint,7,opt,name=lowest_available_checkpoint_objects,json=lowestAvailableCheckpointObjects,proto3,oneof" json:"lowest_available_checkpoint_objects,omitempty"`
	// Software version of the service. Similar to the `server` http header.
	ServerVersion *string `protobuf:"bytes,8,opt,name=server_version,json=serverVersion,proto3,oneof" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceInfoResponse) Reset() {
	*x = GetServiceInfoResponse{}
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceInfoResponse) ProtoMessage() {}

func (x *GetServiceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServiceInfoResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta_ledger_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetServiceInfoResponse) GetChainId() string {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return ""
}

func (x *GetServiceInfoResponse) GetChain() string {
	if x != nil && x.Chain != nil {
		return *x.Chain
	}
	return ""
}

func (x *GetServiceInfoResponse) GetEpoch() uint64 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

func (x *GetServiceInfoResponse) GetCheckpointHeight() uint64 {
	if x != nil && x.CheckpointHeight != nil {
		return *x.CheckpointHeight
	}
	return 0
}

func (x *GetServiceInfoResponse) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetServiceInfoResponse) GetLowestAvailableCheckpoint() uint64 {
	if x != nil && x.LowestAvailableCheckpoint != nil {
		return *x.LowestAvailableCheckpoint
	}
	return 0
}

func (x *GetServiceInfoResponse) GetLowestAvailableCheckpointObjects() uint64 {
	if x != nil && x.LowestAvailableCheckpointObjects != nil {
		return *x.LowestAvailableCheckpointObjects
	}
	return 0
}

func (x *GetServiceInfoResponse) GetServerVersion() string {
	if x != nil && x.ServerVersion != nil {
		return *x.ServerVersion
	}
	return ""
}

type GetObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The `ObjectId` of the requested object.
	ObjectId *string `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3,oneof" json:"object_id,omitempty"`
	// Request a specific version of the object.
	// If no version is specified, and the object is live, then the latest
	// version of the object is returned.
	Version *uint64 `protobuf:"varint,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `object_id,version,digest`.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta_ledger_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetObjectRequest) GetObjectId() string {
	if x != nil && x.ObjectId != nil {
		return *x.ObjectId
	}
	return ""
}

func (x *GetObjectRequest) GetVersion() uint64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *GetObjectRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type BatchGetObjectsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Requests []*GetObjectRequest    `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `object_id,version,digest`.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetObjectsRequest) Reset() {
	*x = BatchGetObjectsRequest{}
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetObjectsRequest) ProtoMessage() {}

func (x *BatchGetObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetObjectsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetObjectsRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta_ledger_service_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetObjectsRequest) GetRequests() []*GetObjectRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *BatchGetObjectsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type BatchGetObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*Object              `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetObjectsResponse) Reset() {
	*x = BatchGetObjectsResponse{}
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetObjectsResponse) ProtoMessage() {}

func (x *BatchGetObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetObjectsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetObjectsResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta_ledger_service_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetObjectsResponse) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

type GetTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The digest of the requested transaction.
	Digest *string `protobuf:"bytes,1,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `digest`.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta_ledger_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransactionRequest) GetDigest() string {
	if x != nil && x.Digest != nil {
		return *x.Digest
	}
	return ""
}

func (x *GetTransactionRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type BatchGetTransactionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The digests of the requested transactions.
	Digests []string `protobuf:"bytes,1,rep,name=digests,proto3" json:"digests,omitempty"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `object_id,version,digest`.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetTransactionsRequest) Reset() {
	*x = BatchGetTransactionsRequest{}
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetTransactionsRequest) ProtoMessage() {}

func (x *BatchGetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta_ledger_service_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetTransactionsRequest) GetDigests() []string {
	if x != nil {
		return x.Digests
	}
	return nil
}

func (x *BatchGetTransactionsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type BatchGetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*ExecutedTransaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetTransactionsResponse) Reset() {
	*x = BatchGetTransactionsResponse{}
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetTransactionsResponse) ProtoMessage() {}

func (x *BatchGetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta_ledger_service_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetTransactionsResponse) GetTransactions() []*ExecutedTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type GetCheckpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If neither is provided, return the latest
	//
	// Types that are valid to be assigned to CheckpointId:
	//
	//	*GetCheckpointRequest_SequenceNumber
	//	*GetCheckpointRequest_Digest
	CheckpointId isGetCheckpointRequest_CheckpointId `protobuf_oneof:"checkpoint_id"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `object_id,version,digest`.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckpointRequest) Reset() {
	*x = GetCheckpointRequest{}
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointRequest) ProtoMessage() {}

func (x *GetCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointRequest.ProtoReflect.Descriptor instead.
func (*GetCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta_ledger_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetCheckpointRequest) GetCheckpointId() isGetCheckpointRequest_CheckpointId {
	if x != nil {
		return x.CheckpointId
	}
	return nil
}

func (x *GetCheckpointRequest) GetSequenceNumber() uint64 {
	if x != nil {
		if x, ok := x.CheckpointId.(*GetCheckpointRequest_SequenceNumber); ok {
			return x.SequenceNumber
		}
	}
	return 0
}

func (x *GetCheckpointRequest) GetDigest() string {
	if x != nil {
		if x, ok := x.CheckpointId.(*GetCheckpointRequest_Digest); ok {
			return x.Digest
		}
	}
	return ""
}

func (x *GetCheckpointRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type isGetCheckpointRequest_CheckpointId interface {
	isGetCheckpointRequest_CheckpointId()
}

type GetCheckpointRequest_SequenceNumber struct {
	// The sequence number of the requested checkpoint.
	SequenceNumber uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3,oneof"`
}

type GetCheckpointRequest_Digest struct {
	// The digest of the requested checkpoint.
	Digest string `protobuf:"bytes,2,opt,name=digest,proto3,oneof"`
}

func (*GetCheckpointRequest_SequenceNumber) isGetCheckpointRequest_CheckpointId() {}

func (*GetCheckpointRequest_Digest) isGetCheckpointRequest_CheckpointId() {}

type GetEpochRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested epoch.
	// If no epoch is provided the current epoch will be returned.
	Epoch *uint64 `protobuf:"varint,1,opt,name=epoch,proto3,oneof" json:"epoch,omitempty"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `epoch`.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEpochRequest) Reset() {
	*x = GetEpochRequest{}
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEpochRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEpochRequest) ProtoMessage() {}

func (x *GetEpochRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta_ledger_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEpochRequest.ProtoReflect.Descriptor instead.
func (*GetEpochRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta_ledger_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetEpochRequest) GetEpoch() uint64 {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return 0
}

func (x *GetEpochRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

var File_sui_rpc_v2beta_ledger_service_proto protoreflect.FileDescriptor

const file_sui_rpc_v2beta_ledger_service_proto_rawDesc = "" +
	"\n" +
	"#sui/rpc/v2beta/ledger_service.proto\x12\x0esui.rpc.v2beta\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fsui/rpc/v2beta/checkpoint.proto\x1a\x1asui/rpc/v2beta/epoch.proto\x1a)sui/rpc/v2beta/executed_transaction.proto\x1a\x1bsui/rpc/v2beta/object.proto\"\x17\n" +
	"\x15GetServiceInfoRequest\"\xc4\x04\n" +
	"\x16GetServiceInfoResponse\x12\x1e\n" +
	"\bchain_id\x18\x01 \x01(\tH\x00R\achainId\x88\x01\x01\x12\x19\n" +
	"\x05chain\x18\x02 \x01(\tH\x01R\x05chain\x88\x01\x01\x12\x19\n" +
	"\x05epoch\x18\x03 \x01(\x04H\x02R\x05epoch\x88\x01\x01\x120\n" +
	"\x11checkpoint_height\x18\x04 \x01(\x04H\x03R\x10checkpointHeight\x88\x01\x01\x12=\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\ttimestamp\x88\x01\x01\x12C\n" +
	"\x1blowest_available_checkpoint\x18\x06 \x01(\x04H\x05R\x19lowestAvailableCheckpoint\x88\x01\x01\x12R\n" +
	"#lowest_available_checkpoint_objects\x18\a \x01(\x04H\x06R lowestAvailableCheckpointObjects\x88\x01\x01\x12*\n" +
	"\x0eserver_version\x18\b \x01(\tH\aR\rserverVersion\x88\x01\x01B\v\n" +
	"\t_chain_idB\b\n" +
	"\x06_chainB\b\n" +
	"\x06_epochB\x14\n" +
	"\x12_checkpoint_heightB\f\n" +
	"\n" +
	"_timestampB\x1e\n" +
	"\x1c_lowest_available_checkpointB&\n" +
	"$_lowest_available_checkpoint_objectsB\x11\n" +
	"\x0f_server_version\"\xb9\x01\n" +
	"\x10GetObjectRequest\x12 \n" +
	"\tobject_id\x18\x01 \x01(\tH\x00R\bobjectId\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\x04H\x01R\aversion\x88\x01\x01\x12<\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskH\x02R\breadMask\x88\x01\x01B\f\n" +
	"\n" +
	"_object_idB\n" +
	"\n" +
	"\b_versionB\f\n" +
	"\n" +
	"_read_mask\"\xa2\x01\n" +
	"\x16BatchGetObjectsRequest\x12<\n" +
	"\brequests\x18\x01 \x03(\v2 .sui.rpc.v2beta.GetObjectRequestR\brequests\x12<\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskH\x00R\breadMask\x88\x01\x01B\f\n" +
	"\n" +
	"_read_mask\"K\n" +
	"\x17BatchGetObjectsResponse\x120\n" +
	"\aobjects\x18\x01 \x03(\v2\x16.sui.rpc.v2beta.ObjectR\aobjects\"\x8b\x01\n" +
	"\x15GetTransactionRequest\x12\x1b\n" +
	"\x06digest\x18\x01 \x01(\tH\x00R\x06digest\x88\x01\x01\x12<\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskH\x01R\breadMask\x88\x01\x01B\t\n" +
	"\a_digestB\f\n" +
	"\n" +
	"_read_mask\"\x83\x01\n" +
	"\x1bBatchGetTransactionsRequest\x12\x18\n" +
	"\adigests\x18\x01 \x03(\tR\adigests\x12<\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskH\x00R\breadMask\x88\x01\x01B\f\n" +
	"\n" +
	"_read_mask\"g\n" +
	"\x1cBatchGetTransactionsResponse\x12G\n" +
	"\ftransactions\x18\x01 \x03(\v2#.sui.rpc.v2beta.ExecutedTransactionR\ftransactions\"\xb8\x01\n" +
	"\x14GetCheckpointRequest\x12)\n" +
	"\x0fsequence_number\x18\x01 \x01(\x04H\x00R\x0esequenceNumber\x12\x18\n" +
	"\x06digest\x18\x02 \x01(\tH\x00R\x06digest\x12<\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskH\x01R\breadMask\x88\x01\x01B\x0f\n" +
	"\rcheckpoint_idB\f\n" +
	"\n" +
	"_read_mask\"\x82\x01\n" +
	"\x0fGetEpochRequest\x12\x19\n" +
	"\x05epoch\x18\x01 \x01(\x04H\x00R\x05epoch\x88\x01\x01\x12<\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskH\x01R\breadMask\x88\x01\x01B\b\n" +
	"\x06_epochB\f\n" +
	"\n" +
	"_read_mask2\x83\x05\n" +
	"\rLedgerService\x12_\n" +
	"\x0eGetServiceInfo\x12%.sui.rpc.v2beta.GetServiceInfoRequest\x1a&.sui.rpc.v2beta.GetServiceInfoResponse\x12E\n" +
	"\tGetObject\x12 .sui.rpc.v2beta.GetObjectRequest\x1a\x16.sui.rpc.v2beta.Object\x12b\n" +
	"\x0fBatchGetObjects\x12&.sui.rpc.v2beta.BatchGetObjectsRequest\x1a'.sui.rpc.v2beta.BatchGetObjectsResponse\x12\\\n" +
	"\x0eGetTransaction\x12%.sui.rpc.v2beta.GetTransactionRequest\x1a#.sui.rpc.v2beta.ExecutedTransaction\x12q\n" +
	"\x14BatchGetTransactions\x12+.sui.rpc.v2beta.BatchGetTransactionsRequest\x1a,.sui.rpc.v2beta.BatchGetTransactionsResponse\x12Q\n" +
	"\rGetCheckpoint\x12$.sui.rpc.v2beta.GetCheckpointRequest\x1a\x1a.sui.rpc.v2beta.Checkpoint\x12B\n" +
	"\bGetEpoch\x12\x1f.sui.rpc.v2beta.GetEpochRequest\x1a\x15.sui.rpc.v2beta.EpochB\x10Z\x0esui/rpc/v2betab\x06proto3"

var (
	file_sui_rpc_v2beta_ledger_service_proto_rawDescOnce sync.Once
	file_sui_rpc_v2beta_ledger_service_proto_rawDescData []byte
)

func file_sui_rpc_v2beta_ledger_service_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2beta_ledger_service_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2beta_ledger_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2beta_ledger_service_proto_rawDesc), len(file_sui_rpc_v2beta_ledger_service_proto_rawDesc)))
	})
	return file_sui_rpc_v2beta_ledger_service_proto_rawDescData
}

var file_sui_rpc_v2beta_ledger_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sui_rpc_v2beta_ledger_service_proto_goTypes = []any{
	(*GetServiceInfoRequest)(nil),        // 0: sui.rpc.v2beta.GetServiceInfoRequest
	(*GetServiceInfoResponse)(nil),       // 1: sui.rpc.v2beta.GetServiceInfoResponse
	(*GetObjectRequest)(nil),             // 2: sui.rpc.v2beta.GetObjectRequest
	(*BatchGetObjectsRequest)(nil),       // 3: sui.rpc.v2beta.BatchGetObjectsRequest
	(*BatchGetObjectsResponse)(nil),      // 4: sui.rpc.v2beta.BatchGetObjectsResponse
	(*GetTransactionRequest)(nil),        // 5: sui.rpc.v2beta.GetTransactionRequest
	(*BatchGetTransactionsRequest)(nil),  // 6: sui.rpc.v2beta.BatchGetTransactionsRequest
	(*BatchGetTransactionsResponse)(nil), // 7: sui.rpc.v2beta.BatchGetTransactionsResponse
	(*GetCheckpointRequest)(nil),         // 8: sui.rpc.v2beta.GetCheckpointRequest
	(*GetEpochRequest)(nil),              // 9: sui.rpc.v2beta.GetEpochRequest
	(*timestamp.Timestamp)(nil),          // 10: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),        // 11: google.protobuf.FieldMask
	(*Object)(nil),                       // 12: sui.rpc.v2beta.Object
	(*ExecutedTransaction)(nil),          // 13: sui.rpc.v2beta.ExecutedTransaction
	(*Checkpoint)(nil),                   // 14: sui.rpc.v2beta.Checkpoint
	(*Epoch)(nil),                        // 15: sui.rpc.v2beta.Epoch
}
var file_sui_rpc_v2beta_ledger_service_proto_depIdxs = []int32{
	10, // 0: sui.rpc.v2beta.GetServiceInfoResponse.timestamp:type_name -> google.protobuf.Timestamp
	11, // 1: sui.rpc.v2beta.GetObjectRequest.read_mask:type_name -> google.protobuf.FieldMask
	2,  // 2: sui.rpc.v2beta.BatchGetObjectsRequest.requests:type_name -> sui.rpc.v2beta.GetObjectRequest
	11, // 3: sui.rpc.v2beta.BatchGetObjectsRequest.read_mask:type_name -> google.protobuf.FieldMask
	12, // 4: sui.rpc.v2beta.BatchGetObjectsResponse.objects:type_name -> sui.rpc.v2beta.Object
	11, // 5: sui.rpc.v2beta.GetTransactionRequest.read_mask:type_name -> google.protobuf.FieldMask
	11, // 6: sui.rpc.v2beta.BatchGetTransactionsRequest.read_mask:type_name -> google.protobuf.FieldMask
	13, // 7: sui.rpc.v2beta.BatchGetTransactionsResponse.transactions:type_name -> sui.rpc.v2beta.ExecutedTransaction
	11, // 8: sui.rpc.v2beta.GetCheckpointRequest.read_mask:type_name -> google.protobuf.FieldMask
	11, // 9: sui.rpc.v2beta.GetEpochRequest.read_mask:type_name -> google.protobuf.FieldMask
	0,  // 10: sui.rpc.v2beta.LedgerService.GetServiceInfo:input_type -> sui.rpc.v2beta.GetServiceInfoRequest
	2,  // 11: sui.rpc.v2beta.LedgerService.GetObject:input_type -> sui.rpc.v2beta.GetObjectRequest
	3,  // 12: sui.rpc.v2beta.LedgerService.BatchGetObjects:input_type -> sui.rpc.v2beta.BatchGetObjectsRequest
	5,  // 13: sui.rpc.v2beta.LedgerService.GetTransaction:input_type -> sui.rpc.v2beta.GetTransactionRequest
	6,  // 14: sui.rpc.v2beta.LedgerService.BatchGetTransactions:input_type -> sui.rpc.v2beta.BatchGetTransactionsRequest
	8,  // 15: sui.rpc.v2beta.LedgerService.GetCheckpoint:input_type -> sui.rpc.v2beta.GetCheckpointRequest
	9,  // 16: sui.rpc.v2beta.LedgerService.GetEpoch:input_type -> sui.rpc.v2beta.GetEpochRequest
	1,  // 17: sui.rpc.v2beta.LedgerService.GetServiceInfo:output_type -> sui.rpc.v2beta.GetServiceInfoResponse
	12, // 18: sui.rpc.v2beta.LedgerService.GetObject:output_type -> sui.rpc.v2beta.Object
	4,  // 19: sui.rpc.v2beta.LedgerService.BatchGetObjects:output_type -> sui.rpc.v2beta.BatchGetObjectsResponse
	13, // 20: sui.rpc.v2beta.LedgerService.GetTransaction:output_type -> sui.rpc.v2beta.ExecutedTransaction
	7,  // 21: sui.rpc.v2beta.LedgerService.BatchGetTransactions:output_type -> sui.rpc.v2beta.BatchGetTransactionsResponse
	14, // 22: sui.rpc.v2beta.LedgerService.GetCheckpoint:output_type -> sui.rpc.v2beta.Checkpoint
	15, // 23: sui.rpc.v2beta.LedgerService.GetEpoch:output_type -> sui.rpc.v2beta.Epoch
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2beta_ledger_service_proto_init() }
func file_sui_rpc_v2beta_ledger_service_proto_init() {
	if File_sui_rpc_v2beta_ledger_service_proto != nil {
		return
	}
	file_sui_rpc_v2beta_checkpoint_proto_init()
	file_sui_rpc_v2beta_epoch_proto_init()
	file_sui_rpc_v2beta_executed_transaction_proto_init()
	file_sui_rpc_v2beta_object_proto_init()
	file_sui_rpc_v2beta_ledger_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_sui_rpc_v2beta_ledger_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_sui_rpc_v2beta_ledger_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_sui_rpc_v2beta_ledger_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_sui_rpc_v2beta_ledger_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_sui_rpc_v2beta_ledger_service_proto_msgTypes[8].OneofWrappers = []any{
		(*GetCheckpointRequest_SequenceNumber)(nil),
		(*GetCheckpointRequest_Digest)(nil),
	}
	file_sui_rpc_v2beta_ledger_service_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2beta_ledger_service_proto_rawDesc), len(file_sui_rpc_v2beta_ledger_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sui_rpc_v2beta_ledger_service_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2beta_ledger_service_proto_depIdxs,
		MessageInfos:      file_sui_rpc_v2beta_ledger_service_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2beta_ledger_service_proto = out.File
	file_sui_rpc_v2beta_ledger_service_proto_goTypes = nil
	file_sui_rpc_v2beta_ledger_service_proto_depIdxs = nil
}
