// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sui/rpc/v2alpha/live_data_service.proto

package v2alpha

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	v2beta "suitop/pb/sui/rpc/v2beta"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DynamicField_DynamicFieldKind int32

const (
	DynamicField_DYNAMIC_FIELD_KIND_UNKNOWN DynamicField_DynamicFieldKind = 0
	DynamicField_FIELD                      DynamicField_DynamicFieldKind = 1
	DynamicField_OBJECT                     DynamicField_DynamicFieldKind = 2
)

// Enum value maps for DynamicField_DynamicFieldKind.
var (
	DynamicField_DynamicFieldKind_name = map[int32]string{
		0: "DYNAMIC_FIELD_KIND_UNKNOWN",
		1: "FIELD",
		2: "OBJECT",
	}
	DynamicField_DynamicFieldKind_value = map[string]int32{
		"DYNAMIC_FIELD_KIND_UNKNOWN": 0,
		"FIELD":                      1,
		"OBJECT":                     2,
	}
)

func (x DynamicField_DynamicFieldKind) Enum() *DynamicField_DynamicFieldKind {
	p := new(DynamicField_DynamicFieldKind)
	*p = x
	return p
}

func (x DynamicField_DynamicFieldKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DynamicField_DynamicFieldKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sui_rpc_v2alpha_live_data_service_proto_enumTypes[0].Descriptor()
}

func (DynamicField_DynamicFieldKind) Type() protoreflect.EnumType {
	return &file_sui_rpc_v2alpha_live_data_service_proto_enumTypes[0]
}

func (x DynamicField_DynamicFieldKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DynamicField_DynamicFieldKind.Descriptor instead.
func (DynamicField_DynamicFieldKind) EnumDescriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{7, 0}
}

// Request message for `NodeService.GetCoinInfo`.
type GetCoinInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The coin type to request information about
	CoinType      *string `protobuf:"bytes,1,opt,name=coin_type,json=coinType,proto3,oneof" json:"coin_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoinInfoRequest) Reset() {
	*x = GetCoinInfoRequest{}
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoinInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoinInfoRequest) ProtoMessage() {}

func (x *GetCoinInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoinInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCoinInfoRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetCoinInfoRequest) GetCoinType() string {
	if x != nil && x.CoinType != nil {
		return *x.CoinType
	}
	return ""
}

// Response message for `NodeService.GetCoinInfo`.
type GetCoinInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The coin type.
	CoinType *string `protobuf:"bytes,1,opt,name=coin_type,json=coinType,proto3,oneof" json:"coin_type,omitempty"`
	// This field will be populated with information about this coin
	// type's `0x2::coin::CoinMetadata` if it exists and has not been wrapped.
	Metadata *CoinMetadata `protobuf:"bytes,2,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	// This field will be populated with information about this coin
	// type's `0x2::coin::TreasuryCap` if it exists and has not been wrapped.
	Treasury *CoinTreasury `protobuf:"bytes,3,opt,name=treasury,proto3,oneof" json:"treasury,omitempty"`
	// If this coin type is a regulated coin, this field will be
	// populated with information about its `0x2::coin::RegulatedCoinMetadata`
	// object.
	RegulatedMetadata *RegulatedCoinMetadata `protobuf:"bytes,4,opt,name=regulated_metadata,json=regulatedMetadata,proto3,oneof" json:"regulated_metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCoinInfoResponse) Reset() {
	*x = GetCoinInfoResponse{}
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoinInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoinInfoResponse) ProtoMessage() {}

func (x *GetCoinInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoinInfoResponse.ProtoReflect.Descriptor instead.
func (*GetCoinInfoResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCoinInfoResponse) GetCoinType() string {
	if x != nil && x.CoinType != nil {
		return *x.CoinType
	}
	return ""
}

func (x *GetCoinInfoResponse) GetMetadata() *CoinMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetCoinInfoResponse) GetTreasury() *CoinTreasury {
	if x != nil {
		return x.Treasury
	}
	return nil
}

func (x *GetCoinInfoResponse) GetRegulatedMetadata() *RegulatedCoinMetadata {
	if x != nil {
		return x.RegulatedMetadata
	}
	return nil
}

// Metadata for a coin type
type CoinMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ObjectId of the `0x2::coin::CoinMetadata` object.
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Number of decimal places to coin uses.
	Decimals *uint32 `protobuf:"varint,2,opt,name=decimals,proto3,oneof" json:"decimals,omitempty"`
	// Name for the token
	Name *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Symbol for the token
	Symbol *string `protobuf:"bytes,4,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	// Description of the token
	Description *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// URL for the token logo
	IconUrl       *string `protobuf:"bytes,6,opt,name=icon_url,json=iconUrl,proto3,oneof" json:"icon_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinMetadata) Reset() {
	*x = CoinMetadata{}
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinMetadata) ProtoMessage() {}

func (x *CoinMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinMetadata.ProtoReflect.Descriptor instead.
func (*CoinMetadata) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{2}
}

func (x *CoinMetadata) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CoinMetadata) GetDecimals() uint32 {
	if x != nil && x.Decimals != nil {
		return *x.Decimals
	}
	return 0
}

func (x *CoinMetadata) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CoinMetadata) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *CoinMetadata) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CoinMetadata) GetIconUrl() string {
	if x != nil && x.IconUrl != nil {
		return *x.IconUrl
	}
	return ""
}

// Information about a coin type's `0x2::coin::TreasuryCap` and its total available supply
type CoinTreasury struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ObjectId of the `0x2::coin::TreasuryCap` object.
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Total available supply for this coin type.
	TotalSupply   *uint64 `protobuf:"varint,2,opt,name=total_supply,json=totalSupply,proto3,oneof" json:"total_supply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinTreasury) Reset() {
	*x = CoinTreasury{}
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinTreasury) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinTreasury) ProtoMessage() {}

func (x *CoinTreasury) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinTreasury.ProtoReflect.Descriptor instead.
func (*CoinTreasury) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{3}
}

func (x *CoinTreasury) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CoinTreasury) GetTotalSupply() uint64 {
	if x != nil && x.TotalSupply != nil {
		return *x.TotalSupply
	}
	return 0
}

// Information about a regulated coin, which indicates that it makes use of the transfer deny list.
type RegulatedCoinMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ObjectId of the `0x2::coin::RegulatedCoinMetadata` object.
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// The ID of the coin's `CoinMetadata` object.
	CoinMetadataObject *string `protobuf:"bytes,2,opt,name=coin_metadata_object,json=coinMetadataObject,proto3,oneof" json:"coin_metadata_object,omitempty"`
	// The ID of the coin's `DenyCap` object.
	DenyCapObject *string `protobuf:"bytes,3,opt,name=deny_cap_object,json=denyCapObject,proto3,oneof" json:"deny_cap_object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegulatedCoinMetadata) Reset() {
	*x = RegulatedCoinMetadata{}
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegulatedCoinMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegulatedCoinMetadata) ProtoMessage() {}

func (x *RegulatedCoinMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegulatedCoinMetadata.ProtoReflect.Descriptor instead.
func (*RegulatedCoinMetadata) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{4}
}

func (x *RegulatedCoinMetadata) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RegulatedCoinMetadata) GetCoinMetadataObject() string {
	if x != nil && x.CoinMetadataObject != nil {
		return *x.CoinMetadataObject
	}
	return ""
}

func (x *RegulatedCoinMetadata) GetDenyCapObject() string {
	if x != nil && x.DenyCapObject != nil {
		return *x.DenyCapObject
	}
	return ""
}

// Request message for `NodeService.ListDynamicFields`
type ListDynamicFieldsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The `UID` of the parent, which owns the collections of dynamic fields.
	Parent *string `protobuf:"bytes,1,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	// The maximum number of dynamic fields to return. The service may return fewer than this value.
	// If unspecified, at most `50` entries will be returned.
	// The maximum value is `1000`; values above `1000` will be coerced to `1000`.
	PageSize *uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// A page token, received from a previous `ListDynamicFields` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `ListDynamicFields` must
	// match the call that provided the page token.
	PageToken     []byte `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDynamicFieldsRequest) Reset() {
	*x = ListDynamicFieldsRequest{}
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDynamicFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDynamicFieldsRequest) ProtoMessage() {}

func (x *ListDynamicFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDynamicFieldsRequest.ProtoReflect.Descriptor instead.
func (*ListDynamicFieldsRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListDynamicFieldsRequest) GetParent() string {
	if x != nil && x.Parent != nil {
		return *x.Parent
	}
	return ""
}

func (x *ListDynamicFieldsRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListDynamicFieldsRequest) GetPageToken() []byte {
	if x != nil {
		return x.PageToken
	}
	return nil
}

// Response message for `NodeService.ListDynamicFields`
type ListDynamicFieldsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page of dynamic fields owned by the specified parent.
	DynamicFields []*DynamicField `protobuf:"bytes,1,rep,name=dynamic_fields,json=dynamicFields,proto3" json:"dynamic_fields,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken []byte `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDynamicFieldsResponse) Reset() {
	*x = ListDynamicFieldsResponse{}
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDynamicFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDynamicFieldsResponse) ProtoMessage() {}

func (x *ListDynamicFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDynamicFieldsResponse.ProtoReflect.Descriptor instead.
func (*ListDynamicFieldsResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListDynamicFieldsResponse) GetDynamicFields() []*DynamicField {
	if x != nil {
		return x.DynamicFields
	}
	return nil
}

func (x *ListDynamicFieldsResponse) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

type DynamicField struct {
	state protoimpl.MessageState         `protogen:"open.v1"`
	Kind  *DynamicField_DynamicFieldKind `protobuf:"varint,1,opt,name=kind,proto3,enum=sui.rpc.v2alpha.DynamicField_DynamicFieldKind,oneof" json:"kind,omitempty"`
	// ObjectId of this dynamic field's parent.
	Parent *string `protobuf:"bytes,2,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	// ObjectId of this dynamic field.
	FieldId *string `protobuf:"bytes,3,opt,name=field_id,json=fieldId,proto3,oneof" json:"field_id,omitempty"`
	// The type of the dynamic field "name"
	NameType *string `protobuf:"bytes,4,opt,name=name_type,json=nameType,proto3,oneof" json:"name_type,omitempty"`
	// The serialized move value of "name"
	NameValue []byte `protobuf:"bytes,5,opt,name=name_value,json=nameValue,proto3,oneof" json:"name_value,omitempty"`
	// The type of the dynamic field "value".
	//
	// If this is a dynamic object field then this is the type of the object
	// itself (which is a child of this field), otherwise this is the type of the
	// value of this field.
	ValueType *string `protobuf:"bytes,6,opt,name=value_type,json=valueType,proto3,oneof" json:"value_type,omitempty"`
	// The ObjectId of the child object when a child is a dynamic
	// object field.
	//
	// The presence or absence of this field can be used to determine if a child
	// is a dynamic field or a dynamic child object
	DynamicObjectId *string `protobuf:"bytes,7,opt,name=dynamic_object_id,json=dynamicObjectId,proto3,oneof" json:"dynamic_object_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DynamicField) Reset() {
	*x = DynamicField{}
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicField) ProtoMessage() {}

func (x *DynamicField) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicField.ProtoReflect.Descriptor instead.
func (*DynamicField) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{7}
}

func (x *DynamicField) GetKind() DynamicField_DynamicFieldKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return DynamicField_DYNAMIC_FIELD_KIND_UNKNOWN
}

func (x *DynamicField) GetParent() string {
	if x != nil && x.Parent != nil {
		return *x.Parent
	}
	return ""
}

func (x *DynamicField) GetFieldId() string {
	if x != nil && x.FieldId != nil {
		return *x.FieldId
	}
	return ""
}

func (x *DynamicField) GetNameType() string {
	if x != nil && x.NameType != nil {
		return *x.NameType
	}
	return ""
}

func (x *DynamicField) GetNameValue() []byte {
	if x != nil {
		return x.NameValue
	}
	return nil
}

func (x *DynamicField) GetValueType() string {
	if x != nil && x.ValueType != nil {
		return *x.ValueType
	}
	return ""
}

func (x *DynamicField) GetDynamicObjectId() string {
	if x != nil && x.DynamicObjectId != nil {
		return *x.DynamicObjectId
	}
	return ""
}

type SimulateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *v2beta.Transaction    `protobuf:"bytes,1,opt,name=transaction,proto3,oneof" json:"transaction,omitempty"`
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateTransactionRequest) Reset() {
	*x = SimulateTransactionRequest{}
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateTransactionRequest) ProtoMessage() {}

func (x *SimulateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateTransactionRequest.ProtoReflect.Descriptor instead.
func (*SimulateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{8}
}

func (x *SimulateTransactionRequest) GetTransaction() *v2beta.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SimulateTransactionRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type SimulateTransactionResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Transaction   *v2beta.ExecutedTransaction `protobuf:"bytes,1,opt,name=transaction,proto3,oneof" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateTransactionResponse) Reset() {
	*x = SimulateTransactionResponse{}
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateTransactionResponse) ProtoMessage() {}

func (x *SimulateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateTransactionResponse.ProtoReflect.Descriptor instead.
func (*SimulateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{9}
}

func (x *SimulateTransactionResponse) GetTransaction() *v2beta.ExecutedTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type ResolveTransactionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UnresolvedTransaction *v2beta.Transaction    `protobuf:"bytes,1,opt,name=unresolved_transaction,json=unresolvedTransaction,proto3,oneof" json:"unresolved_transaction,omitempty"`
	ReadMask              *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ResolveTransactionRequest) Reset() {
	*x = ResolveTransactionRequest{}
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTransactionRequest) ProtoMessage() {}

func (x *ResolveTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTransactionRequest.ProtoReflect.Descriptor instead.
func (*ResolveTransactionRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{10}
}

func (x *ResolveTransactionRequest) GetUnresolvedTransaction() *v2beta.Transaction {
	if x != nil {
		return x.UnresolvedTransaction
	}
	return nil
}

func (x *ResolveTransactionRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

type ResolveTransactionResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Transaction   *v2beta.Transaction          `protobuf:"bytes,1,opt,name=transaction,proto3,oneof" json:"transaction,omitempty"`
	Simulation    *SimulateTransactionResponse `protobuf:"bytes,2,opt,name=simulation,proto3,oneof" json:"simulation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveTransactionResponse) Reset() {
	*x = ResolveTransactionResponse{}
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTransactionResponse) ProtoMessage() {}

func (x *ResolveTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTransactionResponse.ProtoReflect.Descriptor instead.
func (*ResolveTransactionResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{11}
}

func (x *ResolveTransactionResponse) GetTransaction() *v2beta.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ResolveTransactionResponse) GetSimulation() *SimulateTransactionResponse {
	if x != nil {
		return x.Simulation
	}
	return nil
}

type ListOwnedObjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The address of the account that owns the objects.
	Owner *string `protobuf:"bytes,1,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	// Optional type filter to limit the types of objects listed.
	//
	// Providing an object type with no type params will return objects of that
	// type with any type parameter, e.g. `0x2::coin::Coin` will return all
	// `Coin<T>` objects regardless of the type parameter `T`. Providing a type
	// with a type param will retrict the returned objects to only those objects
	// that match the provided type parameters, e.g.
	// `0x2::coin::Coin<0x2::sui::SUI>` will only return `Coin<SUI>` objects.
	ObjectType *string `protobuf:"bytes,4,opt,name=object_type,json=objectType,proto3,oneof" json:"object_type,omitempty"`
	// The maximum number of entries return. The service may return fewer than this value.
	// If unspecified, at most `50` entries will be returned.
	// The maximum value is `1000`; values above `1000` will be coerced to `1000`.
	PageSize *uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// A page token, received from a previous `ListOwnedObjects` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `ListOwnedObjects` must
	// match the call that provided the page token.
	PageToken     []byte `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOwnedObjectsRequest) Reset() {
	*x = ListOwnedObjectsRequest{}
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOwnedObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOwnedObjectsRequest) ProtoMessage() {}

func (x *ListOwnedObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOwnedObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListOwnedObjectsRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListOwnedObjectsRequest) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *ListOwnedObjectsRequest) GetObjectType() string {
	if x != nil && x.ObjectType != nil {
		return *x.ObjectType
	}
	return ""
}

func (x *ListOwnedObjectsRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListOwnedObjectsRequest) GetPageToken() []byte {
	if x != nil {
		return x.PageToken
	}
	return nil
}

type ListOwnedObjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page of dynamic fields owned by the specified parent.
	Objects []*OwnedObject `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken []byte `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOwnedObjectsResponse) Reset() {
	*x = ListOwnedObjectsResponse{}
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOwnedObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOwnedObjectsResponse) ProtoMessage() {}

func (x *ListOwnedObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOwnedObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListOwnedObjectsResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListOwnedObjectsResponse) GetObjects() []*OwnedObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ListOwnedObjectsResponse) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

type OwnedObject struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ObjectId   *string                `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3,oneof" json:"object_id,omitempty"`
	Version    *uint64                `protobuf:"varint,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Digest     *string                `protobuf:"bytes,4,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	Owner      *v2beta.Owner          `protobuf:"bytes,5,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	ObjectType *string                `protobuf:"bytes,6,opt,name=object_type,json=objectType,proto3,oneof" json:"object_type,omitempty"`
	// Current balance if this object is a `0x2::coin::Coin<T>`
	Balance       *uint64 `protobuf:"varint,200,opt,name=balance,proto3,oneof" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnedObject) Reset() {
	*x = OwnedObject{}
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedObject) ProtoMessage() {}

func (x *OwnedObject) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedObject.ProtoReflect.Descriptor instead.
func (*OwnedObject) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP(), []int{14}
}

func (x *OwnedObject) GetObjectId() string {
	if x != nil && x.ObjectId != nil {
		return *x.ObjectId
	}
	return ""
}

func (x *OwnedObject) GetVersion() uint64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *OwnedObject) GetDigest() string {
	if x != nil && x.Digest != nil {
		return *x.Digest
	}
	return ""
}

func (x *OwnedObject) GetOwner() *v2beta.Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *OwnedObject) GetObjectType() string {
	if x != nil && x.ObjectType != nil {
		return *x.ObjectType
	}
	return ""
}

func (x *OwnedObject) GetBalance() uint64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

var File_sui_rpc_v2alpha_live_data_service_proto protoreflect.FileDescriptor

const file_sui_rpc_v2alpha_live_data_service_proto_rawDesc = "" +
	"\n" +
	"'sui/rpc/v2alpha/live_data_service.proto\x12\x0fsui.rpc.v2alpha\x1a google/protobuf/field_mask.proto\x1a)sui/rpc/v2beta/executed_transaction.proto\x1a\x1asui/rpc/v2beta/owner.proto\x1a sui/rpc/v2beta/transaction.proto\"D\n" +
	"\x12GetCoinInfoRequest\x12 \n" +
	"\tcoin_type\x18\x01 \x01(\tH\x00R\bcoinType\x88\x01\x01B\f\n" +
	"\n" +
	"_coin_type\"\xd2\x02\n" +
	"\x13GetCoinInfoResponse\x12 \n" +
	"\tcoin_type\x18\x01 \x01(\tH\x00R\bcoinType\x88\x01\x01\x12>\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1d.sui.rpc.v2alpha.CoinMetadataH\x01R\bmetadata\x88\x01\x01\x12>\n" +
	"\btreasury\x18\x03 \x01(\v2\x1d.sui.rpc.v2alpha.CoinTreasuryH\x02R\btreasury\x88\x01\x01\x12Z\n" +
	"\x12regulated_metadata\x18\x04 \x01(\v2&.sui.rpc.v2alpha.RegulatedCoinMetadataH\x03R\x11regulatedMetadata\x88\x01\x01B\f\n" +
	"\n" +
	"_coin_typeB\v\n" +
	"\t_metadataB\v\n" +
	"\t_treasuryB\x15\n" +
	"\x13_regulated_metadata\"\x86\x02\n" +
	"\fCoinMetadata\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1f\n" +
	"\bdecimals\x18\x02 \x01(\rH\x01R\bdecimals\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06symbol\x18\x04 \x01(\tH\x03R\x06symbol\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x04R\vdescription\x88\x01\x01\x12\x1e\n" +
	"\bicon_url\x18\x06 \x01(\tH\x05R\aiconUrl\x88\x01\x01B\x05\n" +
	"\x03_idB\v\n" +
	"\t_decimalsB\a\n" +
	"\x05_nameB\t\n" +
	"\a_symbolB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_icon_url\"c\n" +
	"\fCoinTreasury\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12&\n" +
	"\ftotal_supply\x18\x02 \x01(\x04H\x01R\vtotalSupply\x88\x01\x01B\x05\n" +
	"\x03_idB\x0f\n" +
	"\r_total_supply\"\xc4\x01\n" +
	"\x15RegulatedCoinMetadata\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x125\n" +
	"\x14coin_metadata_object\x18\x02 \x01(\tH\x01R\x12coinMetadataObject\x88\x01\x01\x12+\n" +
	"\x0fdeny_cap_object\x18\x03 \x01(\tH\x02R\rdenyCapObject\x88\x01\x01B\x05\n" +
	"\x03_idB\x17\n" +
	"\x15_coin_metadata_objectB\x12\n" +
	"\x10_deny_cap_object\"\xa5\x01\n" +
	"\x18ListDynamicFieldsRequest\x12\x1b\n" +
	"\x06parent\x18\x01 \x01(\tH\x00R\x06parent\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\rH\x01R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\fH\x02R\tpageToken\x88\x01\x01B\t\n" +
	"\a_parentB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\xa2\x01\n" +
	"\x19ListDynamicFieldsResponse\x12D\n" +
	"\x0edynamic_fields\x18\x01 \x03(\v2\x1d.sui.rpc.v2alpha.DynamicFieldR\rdynamicFields\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\fH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"\xdd\x03\n" +
	"\fDynamicField\x12G\n" +
	"\x04kind\x18\x01 \x01(\x0e2..sui.rpc.v2alpha.DynamicField.DynamicFieldKindH\x00R\x04kind\x88\x01\x01\x12\x1b\n" +
	"\x06parent\x18\x02 \x01(\tH\x01R\x06parent\x88\x01\x01\x12\x1e\n" +
	"\bfield_id\x18\x03 \x01(\tH\x02R\afieldId\x88\x01\x01\x12 \n" +
	"\tname_type\x18\x04 \x01(\tH\x03R\bnameType\x88\x01\x01\x12\"\n" +
	"\n" +
	"name_value\x18\x05 \x01(\fH\x04R\tnameValue\x88\x01\x01\x12\"\n" +
	"\n" +
	"value_type\x18\x06 \x01(\tH\x05R\tvalueType\x88\x01\x01\x12/\n" +
	"\x11dynamic_object_id\x18\a \x01(\tH\x06R\x0fdynamicObjectId\x88\x01\x01\"I\n" +
	"\x10DynamicFieldKind\x12\x1e\n" +
	"\x1aDYNAMIC_FIELD_KIND_UNKNOWN\x10\x00\x12\t\n" +
	"\x05FIELD\x10\x01\x12\n" +
	"\n" +
	"\x06OBJECT\x10\x02B\a\n" +
	"\x05_kindB\t\n" +
	"\a_parentB\v\n" +
	"\t_field_idB\f\n" +
	"\n" +
	"_name_typeB\r\n" +
	"\v_name_valueB\r\n" +
	"\v_value_typeB\x14\n" +
	"\x12_dynamic_object_id\"\xbc\x01\n" +
	"\x1aSimulateTransactionRequest\x12B\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1b.sui.rpc.v2beta.TransactionH\x00R\vtransaction\x88\x01\x01\x12<\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskH\x01R\breadMask\x88\x01\x01B\x0e\n" +
	"\f_transactionB\f\n" +
	"\n" +
	"_read_mask\"y\n" +
	"\x1bSimulateTransactionResponse\x12J\n" +
	"\vtransaction\x18\x01 \x01(\v2#.sui.rpc.v2beta.ExecutedTransactionH\x00R\vtransaction\x88\x01\x01B\x0e\n" +
	"\f_transaction\"\xdb\x01\n" +
	"\x19ResolveTransactionRequest\x12W\n" +
	"\x16unresolved_transaction\x18\x01 \x01(\v2\x1b.sui.rpc.v2beta.TransactionH\x00R\x15unresolvedTransaction\x88\x01\x01\x12<\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskH\x01R\breadMask\x88\x01\x01B\x19\n" +
	"\x17_unresolved_transactionB\f\n" +
	"\n" +
	"_read_mask\"\xd2\x01\n" +
	"\x1aResolveTransactionResponse\x12B\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1b.sui.rpc.v2beta.TransactionH\x00R\vtransaction\x88\x01\x01\x12Q\n" +
	"\n" +
	"simulation\x18\x02 \x01(\v2,.sui.rpc.v2alpha.SimulateTransactionResponseH\x01R\n" +
	"simulation\x88\x01\x01B\x0e\n" +
	"\f_transactionB\r\n" +
	"\v_simulation\"\xd7\x01\n" +
	"\x17ListOwnedObjectsRequest\x12\x19\n" +
	"\x05owner\x18\x01 \x01(\tH\x00R\x05owner\x88\x01\x01\x12$\n" +
	"\vobject_type\x18\x04 \x01(\tH\x01R\n" +
	"objectType\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\rH\x02R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\fH\x03R\tpageToken\x88\x01\x01B\b\n" +
	"\x06_ownerB\x0e\n" +
	"\f_object_typeB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\x93\x01\n" +
	"\x18ListOwnedObjectsResponse\x126\n" +
	"\aobjects\x18\x01 \x03(\v2\x1c.sui.rpc.v2alpha.OwnedObjectR\aobjects\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\fH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"\xae\x02\n" +
	"\vOwnedObject\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tH\x00R\bobjectId\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\x04H\x01R\aversion\x88\x01\x01\x12\x1b\n" +
	"\x06digest\x18\x04 \x01(\tH\x02R\x06digest\x88\x01\x01\x120\n" +
	"\x05owner\x18\x05 \x01(\v2\x15.sui.rpc.v2beta.OwnerH\x03R\x05owner\x88\x01\x01\x12$\n" +
	"\vobject_type\x18\x06 \x01(\tH\x04R\n" +
	"objectType\x88\x01\x01\x12\x1e\n" +
	"\abalance\x18\xc8\x01 \x01(\x04H\x05R\abalance\x88\x01\x01B\f\n" +
	"\n" +
	"_object_idB\n" +
	"\n" +
	"\b_versionB\t\n" +
	"\a_digestB\b\n" +
	"\x06_ownerB\x0e\n" +
	"\f_object_typeB\n" +
	"\n" +
	"\b_balance2\xa1\x04\n" +
	"\x0fLiveDataService\x12j\n" +
	"\x11ListDynamicFields\x12).sui.rpc.v2alpha.ListDynamicFieldsRequest\x1a*.sui.rpc.v2alpha.ListDynamicFieldsResponse\x12g\n" +
	"\x10ListOwnedObjects\x12(.sui.rpc.v2alpha.ListOwnedObjectsRequest\x1a).sui.rpc.v2alpha.ListOwnedObjectsResponse\x12X\n" +
	"\vGetCoinInfo\x12#.sui.rpc.v2alpha.GetCoinInfoRequest\x1a$.sui.rpc.v2alpha.GetCoinInfoResponse\x12p\n" +
	"\x13SimulateTransaction\x12+.sui.rpc.v2alpha.SimulateTransactionRequest\x1a,.sui.rpc.v2alpha.SimulateTransactionResponse\x12m\n" +
	"\x12ResolveTransaction\x12*.sui.rpc.v2alpha.ResolveTransactionRequest\x1a+.sui.rpc.v2alpha.ResolveTransactionResponseB\x11Z\x0fsui/rpc/v2alphab\x06proto3"

var (
	file_sui_rpc_v2alpha_live_data_service_proto_rawDescOnce sync.Once
	file_sui_rpc_v2alpha_live_data_service_proto_rawDescData []byte
)

func file_sui_rpc_v2alpha_live_data_service_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2alpha_live_data_service_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2alpha_live_data_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2alpha_live_data_service_proto_rawDesc), len(file_sui_rpc_v2alpha_live_data_service_proto_rawDesc)))
	})
	return file_sui_rpc_v2alpha_live_data_service_proto_rawDescData
}

var file_sui_rpc_v2alpha_live_data_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sui_rpc_v2alpha_live_data_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_sui_rpc_v2alpha_live_data_service_proto_goTypes = []any{
	(DynamicField_DynamicFieldKind)(0),  // 0: sui.rpc.v2alpha.DynamicField.DynamicFieldKind
	(*GetCoinInfoRequest)(nil),          // 1: sui.rpc.v2alpha.GetCoinInfoRequest
	(*GetCoinInfoResponse)(nil),         // 2: sui.rpc.v2alpha.GetCoinInfoResponse
	(*CoinMetadata)(nil),                // 3: sui.rpc.v2alpha.CoinMetadata
	(*CoinTreasury)(nil),                // 4: sui.rpc.v2alpha.CoinTreasury
	(*RegulatedCoinMetadata)(nil),       // 5: sui.rpc.v2alpha.RegulatedCoinMetadata
	(*ListDynamicFieldsRequest)(nil),    // 6: sui.rpc.v2alpha.ListDynamicFieldsRequest
	(*ListDynamicFieldsResponse)(nil),   // 7: sui.rpc.v2alpha.ListDynamicFieldsResponse
	(*DynamicField)(nil),                // 8: sui.rpc.v2alpha.DynamicField
	(*SimulateTransactionRequest)(nil),  // 9: sui.rpc.v2alpha.SimulateTransactionRequest
	(*SimulateTransactionResponse)(nil), // 10: sui.rpc.v2alpha.SimulateTransactionResponse
	(*ResolveTransactionRequest)(nil),   // 11: sui.rpc.v2alpha.ResolveTransactionRequest
	(*ResolveTransactionResponse)(nil),  // 12: sui.rpc.v2alpha.ResolveTransactionResponse
	(*ListOwnedObjectsRequest)(nil),     // 13: sui.rpc.v2alpha.ListOwnedObjectsRequest
	(*ListOwnedObjectsResponse)(nil),    // 14: sui.rpc.v2alpha.ListOwnedObjectsResponse
	(*OwnedObject)(nil),                 // 15: sui.rpc.v2alpha.OwnedObject
	(*v2beta.Transaction)(nil),          // 16: sui.rpc.v2beta.Transaction
	(*fieldmaskpb.FieldMask)(nil),       // 17: google.protobuf.FieldMask
	(*v2beta.ExecutedTransaction)(nil),  // 18: sui.rpc.v2beta.ExecutedTransaction
	(*v2beta.Owner)(nil),                // 19: sui.rpc.v2beta.Owner
}
var file_sui_rpc_v2alpha_live_data_service_proto_depIdxs = []int32{
	3,  // 0: sui.rpc.v2alpha.GetCoinInfoResponse.metadata:type_name -> sui.rpc.v2alpha.CoinMetadata
	4,  // 1: sui.rpc.v2alpha.GetCoinInfoResponse.treasury:type_name -> sui.rpc.v2alpha.CoinTreasury
	5,  // 2: sui.rpc.v2alpha.GetCoinInfoResponse.regulated_metadata:type_name -> sui.rpc.v2alpha.RegulatedCoinMetadata
	8,  // 3: sui.rpc.v2alpha.ListDynamicFieldsResponse.dynamic_fields:type_name -> sui.rpc.v2alpha.DynamicField
	0,  // 4: sui.rpc.v2alpha.DynamicField.kind:type_name -> sui.rpc.v2alpha.DynamicField.DynamicFieldKind
	16, // 5: sui.rpc.v2alpha.SimulateTransactionRequest.transaction:type_name -> sui.rpc.v2beta.Transaction
	17, // 6: sui.rpc.v2alpha.SimulateTransactionRequest.read_mask:type_name -> google.protobuf.FieldMask
	18, // 7: sui.rpc.v2alpha.SimulateTransactionResponse.transaction:type_name -> sui.rpc.v2beta.ExecutedTransaction
	16, // 8: sui.rpc.v2alpha.ResolveTransactionRequest.unresolved_transaction:type_name -> sui.rpc.v2beta.Transaction
	17, // 9: sui.rpc.v2alpha.ResolveTransactionRequest.read_mask:type_name -> google.protobuf.FieldMask
	16, // 10: sui.rpc.v2alpha.ResolveTransactionResponse.transaction:type_name -> sui.rpc.v2beta.Transaction
	10, // 11: sui.rpc.v2alpha.ResolveTransactionResponse.simulation:type_name -> sui.rpc.v2alpha.SimulateTransactionResponse
	15, // 12: sui.rpc.v2alpha.ListOwnedObjectsResponse.objects:type_name -> sui.rpc.v2alpha.OwnedObject
	19, // 13: sui.rpc.v2alpha.OwnedObject.owner:type_name -> sui.rpc.v2beta.Owner
	6,  // 14: sui.rpc.v2alpha.LiveDataService.ListDynamicFields:input_type -> sui.rpc.v2alpha.ListDynamicFieldsRequest
	13, // 15: sui.rpc.v2alpha.LiveDataService.ListOwnedObjects:input_type -> sui.rpc.v2alpha.ListOwnedObjectsRequest
	1,  // 16: sui.rpc.v2alpha.LiveDataService.GetCoinInfo:input_type -> sui.rpc.v2alpha.GetCoinInfoRequest
	9,  // 17: sui.rpc.v2alpha.LiveDataService.SimulateTransaction:input_type -> sui.rpc.v2alpha.SimulateTransactionRequest
	11, // 18: sui.rpc.v2alpha.LiveDataService.ResolveTransaction:input_type -> sui.rpc.v2alpha.ResolveTransactionRequest
	7,  // 19: sui.rpc.v2alpha.LiveDataService.ListDynamicFields:output_type -> sui.rpc.v2alpha.ListDynamicFieldsResponse
	14, // 20: sui.rpc.v2alpha.LiveDataService.ListOwnedObjects:output_type -> sui.rpc.v2alpha.ListOwnedObjectsResponse
	2,  // 21: sui.rpc.v2alpha.LiveDataService.GetCoinInfo:output_type -> sui.rpc.v2alpha.GetCoinInfoResponse
	10, // 22: sui.rpc.v2alpha.LiveDataService.SimulateTransaction:output_type -> sui.rpc.v2alpha.SimulateTransactionResponse
	12, // 23: sui.rpc.v2alpha.LiveDataService.ResolveTransaction:output_type -> sui.rpc.v2alpha.ResolveTransactionResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2alpha_live_data_service_proto_init() }
func file_sui_rpc_v2alpha_live_data_service_proto_init() {
	if File_sui_rpc_v2alpha_live_data_service_proto != nil {
		return
	}
	file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[8].OneofWrappers = []any{}
	file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[10].OneofWrappers = []any{}
	file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[12].OneofWrappers = []any{}
	file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[13].OneofWrappers = []any{}
	file_sui_rpc_v2alpha_live_data_service_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2alpha_live_data_service_proto_rawDesc), len(file_sui_rpc_v2alpha_live_data_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sui_rpc_v2alpha_live_data_service_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2alpha_live_data_service_proto_depIdxs,
		EnumInfos:         file_sui_rpc_v2alpha_live_data_service_proto_enumTypes,
		MessageInfos:      file_sui_rpc_v2alpha_live_data_service_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2alpha_live_data_service_proto = out.File
	file_sui_rpc_v2alpha_live_data_service_proto_goTypes = nil
	file_sui_rpc_v2alpha_live_data_service_proto_depIdxs = nil
}
